name: run-script
on: push

jobs:
  script-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: script
        run:  |
          ${GITHUB_WORKSPACE}/getimgs.sh
